### ISSUE TITLE
Unhandled rejection TypeError

### ISSUE THREAD

**Issue by qimingyudaowenti** [aircloud/hexo-theme-aircloud#5]
```
$ hexo server -p 5000
INFO  Start processing
INFO  Hexo is running at http://localhost:5000/. Press Ctrl+C to stop.
Unhandled rejection TypeError: E:\PersonalWeb\themes\aircloud\layout\layout.ejs:39
    37| <script>
    38|     // We expose some of the variables needed by the front end
 >> 39|     window.hexo_search_path = "<%- config.search.path %>"
    40|     window.hexo_root = "<%- config.root %>"
    41|     window.isPost = <%- is_post() %>
    42| </script>

Cannot read property 'path' of undefined
    at eval (eval at compile (E:\PersonalWeb\node_modules\ejs\lib\ejs.js:549:12), <anonymous>:32:31)
    at returnedFn (E:\PersonalWeb\node_modules\ejs\lib\ejs.js:580:17)
    at Theme._View.View._compiled.locals [as _compiled] (E:\PersonalWeb\node_modules\hexo\lib\theme\view.js:124:48)
    at Theme._View.View.View.render (E:\PersonalWeb\node_modules\hexo\lib\theme\view.js:29:15)
    at _compiled.then.result (E:\PersonalWeb\node_modules\hexo\lib\theme\view.js:40:23)
    at tryCatcher (E:\PersonalWeb\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\PersonalWeb\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (E:\PersonalWeb\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (E:\PersonalWeb\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (E:\PersonalWeb\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (E:\PersonalWeb\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (E:\PersonalWeb\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (E:\PersonalWeb\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
```
新手，请问如何解决呢？

**Comment by aircloud** [comment]
首先谢谢你的支持，提出的问题的确存在，目前已经修复(请重新下载本项目)。

**Comment by aircloud** [comment]
由于问题有重复，本issue暂时关闭，可以在 #4 进行讨论
